initial Entry Model
kyeongroe/Journal pull request #2
Opened 2018-07-28 07:17 UTC by kyeongroe

2018-07-30 00:13 UTC, rinndash commented on Journal/Sources/Model/Diary.swift
> +    func showList() {
❗️ 스위프트의 프로토콜의 함수 선언에서는 구현을 포함할 수 없습니다. 수정 부탁드립니다~
```swift
protocol Diary {
  func showList() { }
  //.....
}
```

2018-07-30 00:15 UTC, rinndash commented on Journal/Sources/Model/Entry.swift
> +    var creator: String = "Cool Roe"
❓ 이 일기의 작성자를 Entry마다 설정할 수 있게 쓰셨는데, 만드시려고 하는 일기장 앱은 여러 명이 같이 사용하는 일기장인가요?

2018-07-30 00:19 UTC, rinndash commented on Journal/Sources/Model/Entry.swift
> +    var id: String
`Entry`는 엔티티이고 엔티티는 id로 같음과 다름을 식별하니 `id`가 바뀔 수 있으면 안되겠죠? `var`보다는 `let`을 사용하시는 게 적절할 것 같습니다.

2018-07-30 00:26 UTC, rinndash requested changes
`Diary` 프로토콜 수정 부탁드립니다

2018-07-30 00:57 UTC, kyeongroe commented on Journal/Sources/Model/Entry.swift
> +    var creator: String = "Cool Roe"
싱크를 날린다거나 했을 때 중앙화된 스토리지에 저장이 되려면 뭔가 있어야 하지 않을까 싶어서요

2018-07-30 12:58 UTC, rinndash commented on Journal/Sources/Model/Diary.swift
> +    func showDetail(Entry entry)
❗️ 스위프트는 함수의 파라미터를 `파라미터 이름: 타입`으로 씁니다. 아래처럼 고쳐쓰셔야 합니다.

```swift
func showDetail(entry: Entry)
```

2018-07-30 12:59 UTC, rinndash requested changes
프로토콜 선언에 오류가 있네요. 수정하시고 꼭 컴파일이 되는지 확인해보시는 것이 좋습니다.

2018-07-30 13:01 UTC, rinndash commented on Journal/Sources/Model/Entry.swift
> +    var creator: String = "Cool Roe"
넵. 말씀하신 부분은 나중에 필요합니다. 구현하신 방법과는 다르게 처리할 수 있겠지만 일단은 이대로 진행하셔도 좋습니다.

2018-07-31 06:07 UTC, kyeongroe commented
이게 어디에 코멘트를 달아야 할지 익숙치 않네요

2018-07-31 14:11 UTC, rinndash commented
써주신 것처럼 달아주시면 됩니다 :)

2018-07-31 14:13 UTC, rinndash commented on JournalTests/JournalTests.swift
> +
아래의 Entry 선언을 제거하고

```swift
@testable import Journal
```
을 추가하면 `Journal` 타겟의 Entry 클래스를 테스트에서 사용하실 수 있습니다

2018-07-31 14:14 UTC, rinndash approved these changes

2018-08-04 01:38 UTC, merged